generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Proyecto
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          proyecto_proyecto
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display:           [nombre, organizacion]
        object_actions:
          _edit:           ~
          _delete:         ~
          sync:            { label: Importar desde repositorio, action: sync }
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
