generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Catalogo
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          catalogo_psdfCatalogo
    with_doctrine_route:     1

    config:
      actions: ~
      fields:
        definicion:        { attributes: { cols: 80, rows: 20 } }
      list:    ~
      filter:  ~
      form:    ~ 
      edit:    ~
      new:     ~
